# docker-compose.prod.yml - Production конфигурация

version: '3.8'

services:
  backend:
    image: militaryfocus/ml-community-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ml_user:${POSTGRES_PASSWORD}@db:5432/ml_community
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
      - DEBUG=false
    depends_on:
      - db
      - redis
    restart: unless-stopped

  frontend:
    image: militaryfocus/ml-community-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=ml_community
      - POSTGRES_USER=ml_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: